Add Brazilian Portuguese translation
iman-salmani/iplan pull request #12
Opened 2023-05-24 23:11 UTC by Penfore

2023-05-25 09:21 UTC, iman-salmani commented
Thanks for your contribution.
Some texts were added or fixed, Please update the translation.
you can update the file by running this command on _build folder:
```bash
meson compile iplan-update-po
```

2023-05-27 03:34 UTC, Penfore commented
Hello, @iman-salmani 

I have updated the translation with the added and modified texts.

2023-05-27 04:49 UTC, iman-salmani requested changes

2023-05-27 04:49 UTC, iman-salmani commented on po/pt_BR.po
> +msgstr "Use o menu principal"
The format of this text changed. Now it uses `{}` for adding a shortcut label instead of splitting text.

2023-05-27 04:49 UTC, iman-salmani commented on po/pt_BR.po
> +#~ msgid "for adding new lists"
No longer needed

2023-05-27 05:28 UTC, iman-salmani requested changes
The branch was updated, but some texts are missing. make sure you executed this command.
```bash
cd _build                
meson compile iplan-update-po
```
Some texts in the `data/ir.imansalmani.IPlan.metainfo.xml` file, are release changes you can ignore them if you wish.
> I'm not sure if release changes should be translated or not.

2023-05-27 05:29 UTC, iman-salmani commented
Hello, @Penfore
commit f3de09e95539a4152a33c2b71bbcf8bcda698174
Thank you, pull request needs some changes.

2023-05-27 18:16 UTC, Penfore commented
Hello, @iman-salmani! 
I'm sorry for the confusion, I have messes up my files when switching between Builder and GTranslator. Let me know if there is still something wrong. 

Also, I can make a new PR to keep the repo clean if you want.

2023-05-28 05:04 UTC, iman-salmani requested changes
Thank you for your contribution
> Also, I can make a new PR to keep the repo clean if you want.
no need. (squash and merge)

2023-05-28 05:05 UTC, iman-salmani approved these changes
Thank you for your contribution
> Also, I can make a new PR to keep the repo clean if you want.
no need. (squash and merge)

2023-05-28 05:06 UTC, merged