Add Russian language support
iman-salmani/iplan pull request #50
Opened 2023-07-15 18:49 UTC by SokolovskyMaxim

2023-07-15 19:54 UTC, iman-salmani requested changes
Thank you for your contribution
meta info texts are unnecessary but some texts in UI seem to be forgotten. I pointed them out in the following messages.
Also, you can add your name below `translator-credits` message-id to be shown in the About window.

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
☝🏻

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
☝🏻

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
☝🏻

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
☝🏻

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
☝🏻

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
☝🏻

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
☝🏻

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
☝🏻

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
☝🏻

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
☝🏻

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
☝🏻

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
Here you can add your name to the About page. in one of these formats:
```
Your Name https://example.com
Your Name <example@mail.com>
```

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
☝🏻

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
☝🏻

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +msgstr ""
☝🏻

2023-07-15 19:54 UTC, iman-salmani commented on po/ru.po
> +"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
You can also put your name here ☝🏻

2023-07-16 05:05 UTC, SokolovskyMaxim commented
> meta info texts are unnecessary

how should I distinguish meta information from the interface?

2023-07-16 09:37 UTC, iman-salmani commented
metainfo.xml file contains app data to show in app stores and I'm not sure if I'm doing this wrong or if App stores like Flathub do not support translation for app info.
If they support them I will exclude the release notes part from the translation files.
And if not meta info will be excluded.

You can find out where text is used by looking top of the msgid in the po file.
In case you using Poedit, right-click on the text.

2023-07-16 09:38 UTC, merged